"""Remove version_code and min_supported_version from app_versions

Revision ID: b4ac8dc12257
Revises: addae56fc57a
Create Date: 2025-10-20 13:14:26.499899+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ac8dc12257'
down_revision: Union[str, None] = 'addae56fc57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_versions', 'min_supported_version')
    op.drop_column('app_versions', 'version_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_versions', sa.Column('version_code', sa.INTEGER(), autoincrement=False, nullable=False, comment='버전 코드 (빌드 번호)'))
    op.add_column('app_versions', sa.Column('min_supported_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='지원 최소 버전'))
    # ### end Alembic commands ###