"""Add app_versions table for app version management

Revision ID: addae56fc57a
Revises: 1a2b3c4d5e6f
Create Date: 2025-10-20 13:07:29.005987+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addae56fc57a'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diaries', 'ocr_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               comment=None,
               existing_comment='손글씨 인식으로 추출된 원본 텍스트',
               existing_nullable=True)
    op.add_column('password_reset_tokens', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'used_at')
    op.alter_column('diaries', 'ocr_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               comment='손글씨 인식으로 추출된 원본 텍스트',
               existing_nullable=True)
    # ### end Alembic commands ###